using System;
using System.Linq;
using NLogCentral.Web.Models;
using Raven.Client.Indexes;

namespace NLogCentral.Web.Indexes
{
    public class LogModelCountByLevelPerHour : AbstractIndexCreationTask<LogModel, LogModelCountByLevelPerHour.ReduceResult>
    {
        public class ReduceResult
        {
            public long Hour { get; set; }
            public string Level { get; set; }
            public int Count { get; set; }
        }

        // The index name generated by this is going to be BlogPosts/PostsCountByTag
        public LogModelCountByLevelPerHour()
        {
            
            Map = logs => from log in logs
                           select new
                           {
                               Hour = log.Date.Ticks / TimeSpan.TicksPerHour,
                               Level = log.Level,
                               Count = 1
                           };

            Reduce = results => from result in results
                                group result by new {result.Hour, result.Level}
                                    into g
                                    select new
                                    {
                                        Hour = g.Key.Hour,
                                        Level = g.Key.Level,
                                        Count = g.Sum(x => x.Count)
                                    };
        }
    }
}